name: "My Shared Steps"
description: "Reusable steps"

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer:v2
        coverage: pcov

    - name: Get Composer Cache Directory
      id: composer_cache_directory
      run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Composer Dependencies
      uses: actions/cache@v4
      with:
        key: composer-cache-${{ hashFiles('./composer.lock') }}
        path: ${{ steps.composer_cache_directory.outputs.dir }}
        restore-keys: composer-cache-

    - name: Install Composer Dependencies
      run: composer install:ci
      shell: bash
