name: JS Tests

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_call:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Composer
        uses: ./.github/actions/composer-install

      - name: Prepare Environment
        run: composer test:deps

      - name: Generate Routes
        env:
          CACHE_STORE: ${{ vars.CACHE_STORE }}
          DB_CONNECTION: ${{ vars.DB_CONNECTION }}
          DB_DATABASE: ${{ vars.DB_DATABASE }}
        run: composer wayfinder:gen

      - name: Install Node Dependencies
        run: npm ci

      - name: Test JS
        run: npm run test
