name: PHP Tests

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_call:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Aspell
        uses: ConorMacBride/install-package@v1
        with:
          apt: aspell

      - name: Prepare Composer
        uses: ./.github/actions/composer-install

      - name: Prepare Environment
        run: composer test:deps

      - name: Prepare Tests
        env:
          CACHE_STORE: ${{ vars.CACHE_STORE }}
          DB_CONNECTION: ${{ vars.DB_CONNECTION }}
          DB_DATABASE: ${{ vars.DB_DATABASE }}
        run: composer test:prep

      - name: Test PHP
        run: composer test
